# If you need a more in-depth explanation of these options, please look at https://github.com/Simplexity-Development/SimpleVeinMining/blob/master/README.md
allowed-blocks:
  - "minecraft:coal_ore"
  - "minecraft:coal_block"
  - "minecraft:deepslate_coal_ore"
  - "minecraft:copper_ore"
  - "minecraft:deepslate_copper_ore"
  - "minecraft:raw_copper_block"
  - "minecraft:diamond_ore"
  - "minecraft:deepslate_diamond_ore"
  - "minecraft:emerald_ore"
  - "minecraft:deepslate_emerald_ore"
  - "minecraft:gold_ore"
  - "minecraft:raw_gold_block"
  - "minecraft:deepslate_gold_ore"
  - "minecraft:iron_ore"
  - "minecraft:raw_iron_block"
  - "minecraft:deepslate_iron_ore"
  - "minecraft:lapis_ore"
  - "minecraft:deepslate_lapis_ore"
  - "minecraft:redstone_ore"
  - "minecraft:deepslate_redstone_ore"
  - "minecraft:nether_gold_ore"
  - "minecraft:nether_quartz_ore"
  - "minecraft:ancient_debris"
allowed-blocks-is-blacklist: false
same-type: true
types:
  coal:
    - "minecraft:coal_ore"
    - "minecraft:coal_block"
    - "minecraft:deepslate_coal_ore"
  copper:
    - "minecraft:copper_ore"
    - "minecraft:deepslate_copper_ore"
    - "minecraft:raw_copper_block"
  diamond:
    - "minecraft:diamond_ore"
    - "minecraft:deepslate_diamond_ore"
  emerald:
    - "minecraft:emerald_ore"
    - "minecraft:deepslate_emerald_ore"
  gold:
    - "minecraft:gold_ore"
    - "minecraft:raw_gold_block"
    - "minecraft:deepslate_gold_ore"
  iron:
    - "minecraft:iron_ore"
    - "minecraft:raw_iron_block"
    - "minecraft:deepslate_iron_ore"
  lapis:
    - "minecraft:lapis_ore"
    - "minecraft:deepslate_lapis_ore"
  redstone:
    - "minecraft:redstone_ore"
    - "minecraft:deepslate_redstone_ore"
works-in-creative: false
damage-tool:
  prevent-breaking: true
require-proper-tool: true
require-lore:
  enabled: false
  lore: "<white>Vein Mining</white>"
require-item-model:
  enabled: false
  valid-models:
    - "minecraft:stick"
max-blocks-to-break: 64
ignore-protections: false
crouch-prevents-vein-mining: true
drop-at-mined-location: false
