name: SimpleVeinMining
version: '${project.version}'
main: simplexity.simpleveinmining.SimpleVeinMining
author: RhythmicSystem
api-version: '1.21'
load: STARTUP
softdepend:
  - WorldGuard
  - CoreProtect
description: A simple plugin with configuration options for vein mining.
website: https://github.com/Simplexity-Development/SimpleVeinMining
permissions:
  veinmining.mining:
    default: op
    description: Allows the player to use the vein mining functionality
  veinmining.reload:
    default: op
    description: Allows the player to reload the plugin
  veinmining.toggle:
    default: op
    description: Allows player to toggle vein mining off/on for themselves
commands:
  vmreload:
    permission: veinmining.reload
    description: Allows the player to reload the plugin
  vmtoggle:
    permission: veinmining.toggle
    description: Allows player to toggle vein mining off/on for themselves
